### ISSUE TITLE
Token authentication sample code.

### ISSUE THREAD

**Issue by Ashwin-Kapes** [cyotek/MantisSharp#4]
Can you provide sample code to authenticate using token  I'm using header to send token but it's still using cookie authentication.

**Comment by cyotek** [comment]
Hello,

The only way this library works is through token authentication - every HTTP request made by the library includes the `Authorization` header containing the specified API key. No cookie containers are set up or processed.

How are you calling the library? What sort of output are you getting returned? Have you tried using the sample Browser application with the URL of your MantisBT instance along with an appropriate API key?

Regards;
Richard Moss

**Comment by cyotek** [comment]
No response, closing.
